#!/bin/sh
echo "[post-rewrite hook: $1]"

# quick script to call "git submodule update" automatically if the
# .gitmodules file is changed
# CREDIT: https://gist.github.com/digitaljhelms/f74eaf56835262d6bf3f

changedfiles=( `git diff-tree --no-commit-id --name-only HEAD@{1} HEAD` )

if [[ "${changedfiles[*]}" =~ ".gitmodules" ]]; then
    echo "initializing & updating submodule(s)"
    git submodule update --init --recursive
fi
