#!/usr/bin/env python
# Command to run tests
# Runs inside Docker container so we can depend on library availabilty.
import os
from sys import argv, exit
from subprocess import run
from shlex import split
from time import sleep
from requests import get
from click import echo
from requests.exceptions import ConnectionError

args = argv[1:]

def site_ready():
    try:
        res = get("http://frontend:8000/")
        return res.status_code == 200
    except ConnectionError:
        return False

counter = 0
while not site_ready():
    if counter > 30:
        # Exit with error code
        exit(1)

    echo(".", nl=False)
    sleep(1)
    counter += 1

print("Running tests")
run(["pytest", "/test", *args])
