#!/usr/bin/env python3
# Description: Build docker base images
from os import chdir, path
from textwrap import dedent
from sys import argv, exit
from subprocess import call

b = lambda x: '\033[1m'+x+'\033[0m'

def cmd(*command):
    c = " ".join(command)
    print(c)
    return call(c, shell=True)

chdir(path.dirname(path.realpath(__file__)))
argv.pop(0)

if len(argv) == 0:
    print(dedent("""
        Usage: sparrow-build [--push] <image>
        <image> should be one of
        - backend
        - db-mysql-fdw
            """))
    exit(0)

push = False
if '--push' in argv:
    push = True

IMAGES = {
  "backend": "sparrowdata/backend-base:1.2",
  "db-mysql-fdw": "sparrowdata/db-mysql-fdw:1.0"
}

for arg in argv:
    if arg == '--push':
        continue
    im = IMAGES[arg]
    print(arg+": building image "+b(im))
    cmd("docker build -t "+im+" "+arg)
    if push:
        cmd("docker push "+im)
