[tool.black]
line-length = 88
skip-magic-trailing-comma = true
target-version = ['py38']

[tool.pylint.messages_control]

max-line-length = 88

disable = [
  "missing-docstring",
  "missing-class-docstring",
  "too-few-public-methods",
]