# Modifies containers for dev hot reloading
version: "3.6"
services:
  gateway:
    volumes:
      - ./nginx-config/locations/frontend-development.conf:/etc/nginx/locations/frontend.conf:ro
  frontend:
    build:
      context: frontend
    command: npm run dev:docker
    expose:
      - 3000
    volumes:
      # Extra bind mounts to local directories for code reloading
      - ./frontend/src:/app/src
      - ./frontend/packages:/app/packages
      - ./frontend/plugins:/app/plugins
      - ./frontend/static:/app/static
      - ./frontend/package.json:/app/package.json:ro
      - ./frontend/yarn.lock:/app/yarn.lock:ro
      # Keep node_modules in a volume to speed up rebuilding
      - frontend_yarn_cache:/app/.yarn/cache
volumes:
  frontend_yarn_cache:
