# A configuration snippet to allow loading user-provided SSL certificates.
version: "3.6"
services:
  gateway:
    image: nginx:1.23.0
    ports:
      - ${SPARROW_HTTP_PORT:-80}:80
      - ${SPARROW_HTTPS_PORT:-443}:443
    environment:
      # These environment variables will be added via envsubst
      - SPARROW_DOMAIN
      - SPARROW_CERTIFICATE=/etc/certificates/fullchain.pem
      - SPARROW_CERTIFICATE_KEY=/etc/certificates/privkey.pem
    volumes:
      # This file will be templated by ENVSUBST and output to conf.d
      - ./nginx-config/templates/default-ssl.conf:/etc/nginx/templates/default.conf.template:ro
      - ${SPARROW_CERTIFICATE}:/etc/certificates/fullchain.pem:ro
      - ${SPARROW_CERTIFICATE_KEY}:/etc/certificates/privkey.pem:ro
