# Modifies containers for dev hot reloading
version: "3.6"
services:
  frontend:
    build:
      context: frontend
      target: base
    volumes:
      - frontend_node_modules:/app/node_modules
      # Right now, we configure default site content
      # rather than allowing any customization
      - ${SPARROW_SITE_CONTENT:-./frontend/default-content}:/app/site-content
      # A folder for a testing version of the @macrostrat/ui-components
      # Javascript library that will be linked into the container at runtime
      # to support tandem development within Docker
      - ${SPARROW_UI_COMPONENTS:-placeholder}:/app/_local_modules/@macrostrat/ui-components:ro
      - ./frontend:/app
volumes:
  frontend_node_modules:
  placeholder: