# Modifies containers for dev hot reloading
version: "3.6"
services:
  frontend:
    build:
      context: frontend
    command: npm run dev:docker
    volumes:
      - ./nginx-config/locations/development.conf:/etc/nginx/locations/development.conf:ro
      # Extra bind mounts to local directories for code reloading
      - ./frontend/src:/app/src
      - ./frontend/packages:/app/packages
      - ./frontend/plugins:/app/plugins
      - ./frontend/_webpack:/app/_webpack
      - ./frontend/static:/app/static
      # Keep node_modules in a container to facilitate rebuilding
      - frontend_node_modules:/app/node_modules
volumes:
  frontend_node_modules:
