services:
  # Add a production server for static files
  # Set restart policy to allow docker
  # to bring these containers back up on system
  # reboot.
  gateway:
    restart: unless-stopped
  backend:
    restart: unless-stopped
  db:
    restart: unless-stopped
  pg_api:
    restart: unless-stopped
  frontend:
    restart: unless-stopped
  worker:
    restart: unless-stopped
  broker:
    restart: unless-stopped
