version: "3.6"
services:
  gateway:
    image: staticfloat/nginx-certbot:latest
    ports:
      - ${SPARROW_HTTP_PORT:-80}:80
      - ${SPARROW_HTTPS_PORT:-443}:443
    environment:
      - CERTBOT_EMAIL
      # Substitute in value for SPARROW_DOMAIN
      - ENVSUBST_VARS=SPARROW_DOMAIN
      - SPARROW_DOMAIN
    volumes:
      - ./nginx-config/certbot-ssl.conf:/etc/nginx/user.conf.d/site.conf:ro
