#!/usr/bin/env bash

# Install poetry if not already installed
if ! command -v poetry &> /dev/null
then
  python3 _cli/_scripts/install-poetry.py
  export PATH="$HOME/.local/bin:$PATH"
fi

# Meant to be run from the repository root folder
cd _cli
poetry install
