#!/usr/bin/env bash

# Meant to be run from the repository root folder
mkdir -p _cli/build
venv=_cli/build/venv

unset VIRTUAL_ENV
if [ ! -f $venv/bin/activate ]; then
  python3 -m venv $venv
fi
source $venv/bin/activate
python3 -m pip install -r _cli/requirements.txt

