#!/usr/bin/env bash

# Meant to be run from the repository root folder
_cli/_scripts/build-local
# Activate virtual environment without actually activating
export VIRTUAL_ENV="$(pwd)/_cli/build/venv"
export PATH="$VIRTUAL_ENV/bin:$PATH"

python3 -m pip install pyinstaller==4.2
cd _cli
pyinstaller --noconfirm --distpath dist sparrow.spec
cd dist
du -h -d 2 sparrow
