#!/usr/bin/env bash

install_path=${SPARROW_INSTALL_PATH:-${INSTALL_PATH:-/usr/local}}
build_dir=_cli/dist/sparrow
dist_dir=${1:-$install_path/opt/sparrow}
symlink=${2:-$install_path/bin/sparrow}
executable=${dist_dir}/sparrow

# We build as a folder rather than a single zipped file due to MacOS Catalina issues
# This is related to OSX 'phoning home' for security when unknown programs are run.
# https://github.com/docker/compose/issues/6956

if [ ! -d $build_dir ]; then
  # Build the local module
  _cli/_scripts/build-local
fi

if [ -d $dist_dir ]; then
  read -p "$dist_dir already exists. Overwrite? yN " -n 1 -r
  echo    # (optional) move to a new line
  [[ $REPLY =~ ^[Yy]$ ]] && rm -rf $dist_dir
fi

[ -L $symlink ] && rm -f $symlink

if [ -e $symlink ]; then
  read -p "$symlink already exists. Overwrite? yN " -n 1 -r
  echo    # (optional) move to a new line
  [[ $REPLY =~ ^[Yy]$ ]] && rm -rf $symlink
fi

mkdir -p "$dist_dir"
mkdir -p "$(dirname "$symlink")"
# Copy all files and dependencies to a centralized location
rm -rf "$dist_dir"
cp -r "$build_dir" "$dist_dir"

# Link executable onto the path
echo "Linking $symlink -> $executable"
ln -sf "$executable" "$symlink"
