# Simplejson's encoder supports decimals
from simplejson import JSONEncoder

from flask import Flask, Blueprint
from flask_restful import Resource, Api
from sqlalchemy.schema import Table

from .database import Database

def build_autogenerated_routes(api, db):

    table = Table('datum', db.meta, autoload=True, autoload_with=db.engine)
    q = db.session.query(table)

    class DatumTable(Resource):
        def get(self):
            return q.limit(1000).all()

    api.add_resource(DatumTable, '/')

def construct_app(database):
    app = Flask(__name__)
    # Set JSON encoder

    api_blueprint = Blueprint('api', __name__)
    api = Api(api_blueprint)

    # Kind of a kludge to get things running
    db = Database(database)
    app.db = db

    build_autogenerated_routes(api, db)

    app.register_blueprint(api_blueprint, url_prefix='/api/v1')
    app.config['RESTFUL_JSON'] = dict(cls=JSONEncoder)
    return app
