#!/bin/sh
# Script to build the uncooperatative dependencies needed
# for the Sparrow backend
# Note: `apk` is the package-management equivalent of `apt`
# for Alpine Linux.
apk update
apk upgrade
apk add --no-cache libstdc++ openblas \
    libpq postgresql-dev postgresql-client
apk add --no-cache --virtual=build_deps g++ gfortran \
    musl-dev python3-dev openblas-dev
    ln -s /usr/include/locale.h /usr/include/xlocale.h

# On a normal system, these installation commands
# would likely work fine out of the box
pip3 install --no-cache-dir numpy
pip3 install --no-cache-dir pandas
pip3 install --no-cache-dir psycopg2

# Get rid of extra dependencies
rm /usr/include/xlocale.h
apk del build_deps

