#! /usr/bin/env sh

set -e

cd /app

HOST=0.0.0.0
PORT=5000

# Wait a tick to allow us to echo
# (this is kind of a hack and may cause problems)
sleep 1
echo "Running backend in $SPARROW_ENV mode"
if [ $SPARROW_ENV = 'development' ]; then
  ## Could also try hypercorn for better reloading...
  exec hypercorn \
    -w 1 \
    --config python:sparrow.logs.config \
    --reload \
    --bind $HOST:$PORT \
    "sparrow.__entry__:app"
else
  exec hypercorn --bind $HOST:$PORT \
    -w 1 \
    --log-file - \
    --log-level warning \
    "sparrow.__entry__:app"
fi