#!/bin/sh

cd /app

while ! pg_isready -h db -p 5432 -U postgres ; do
  echo "Waiting for database..."
  sleep 1
done

# We no longer import EarthChem vocabularies by default

# (non-foolproof) check for whether tables exist
res=$(psql -tA -h db -p 5432 -U postgres sparrow -c "
SELECT EXISTS (
  SELECT *
  FROM information_schema.tables
  WHERE table_schema = 'public'
    AND table_name = 'datum'
);")

# Create tables if they don't exist
[ ! $res = 't' ] && python3 sparrow init

#gunicorn -w 4 -k uvicorn.workers.UvicornWorker --log-level warning sparrow:app
uvicorn --reload --port 5000 --host 0.0.0.0 sparrow.asgi:app
