#!/usr/bin/env python
# Command to run tests
# Runs inside Docker container so we can depend on library availabilty.
import os
from sys import argv, exit
from click import echo
from subprocess import run
from time import sleep

args = argv[1:]

psql = False
if "--psql" in args:
    psql = True
    args.remove("--psql")

os.chdir("/app")

print("Running tests")
res = run(["pytest", "/app/sparrow_tests", *args])

if psql:
    echo("Initializing psql shell. " "The database is also available on localhost port 54322")
    run(["psql", *dbargs, "sparrow_test"])

exit(res.returncode)
