#!/usr/bin/env python
# Copied from 'davenquinn/paper-components'
import re
import sys

cite_re = re.compile(r'@[\w-]+')
keys = set(['@fig','@sec','@eq','@tbl'])
for line in sys.stdin:
    citekeys = re.findall(cite_re, line)
    for key in citekeys:
        if key not in keys:
          print(key[1:])
keys.add(key)
