#!/bin/bash
# Description: Test round-trip data import export functionality

# Switching from zsh to (less expressive) bash
# https://stackoverflow.com/questions/59895
DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"

# This script runs on the host system and kicks off the
# import process within a docker container
import_pipeline="$DIR"

# Run within container, mounting Sparrow data directory
# and importer code.
sparrow compose run \
  -e "SPARROW_DATA_DIR=/Data" \
  -e "PYTHONPATH=/import-pipeline" \
  -v "$SPARROW_DATA_DIR:/Data:ro" \
  -v "$import_pipeline:/import-pipeline" \
  backend \
  python -m test_importer
