- var: SPARROW_INSTALL_PATH
  description: Base path for sparrow installation
  defaults: $INSTALL_PATH, /usr/local
- SPARROW_DOMAIN
- SPARROW_BASE_URL
- SPARROW_COMMANDS
- CERTBOT_EMAIL
- SPARROW_BACKUP_DIR
- var: SPARROW_CONFIG_DIR
  description: >
    The directory that the `sparrow-config.sh` file resides in.
    This is automatically set by the `sparrow` command-line application,
    so it can be used in 