#!/bin/sh
# Script to build the uncooperatative dependencies needed
# for the Sparrow backend
# Note: `apk` is the package-management equivalent of `apt`
# for Alpine Linux.
apk update
apk upgrade
apk add --no-cache python3-dev libstdc++ openblas \
    libpq postgresql-dev postgresql-client libxslt-dev
apk add --no-cache --virtual .build_deps gcc g++ gfortran \
    musl-dev python3-dev openblas-dev libxml2-dev
ln -s /usr/include/locale.h /usr/include/xlocale.h

pip install --no-cache-dir lxml==4.3.1
pip install --no-cache-dir numpy==1.16.1
pip install --no-cache-dir pandas==0.24.1
pip install --no-cache-dir psycopg2==2.7.7

rm /usr/include/xlocale.h
apk del .build_deps
