#!/bin/sh

sleep 0.1
# Link @macrostrat/ui-components submodule from a mounted directory,
# if it exists.
ui_components=/app/_local_modules/ui-components
dest=/app/node_modules/@macrostrat/ui-components
if [ -e $ui_components/package.json ]; then
  echo "Using a locally-linked version of @macrostrat/ui-components"
  rm -rf "$dest"
  ln -s "$ui_components" "$dest"
fi

webpack
