#!/usr/bin/env python
"""
Import script to load detrital zircon data for the Naukluft Nappe Complex, Namibia
directly from the local project-specific PostgreSQL database.
"""

from sqlalchemy import create_engine
from labdata.util import run_query

db = create_engine("postgresql:///Naukluft")
df = run_query(db, "SELECT * FROM detrital_zircon")

import IPython; IPython.embed(); raise

