from .utils import construct_schema_fields_object, get_schema_field_items
from ..api_info import get_field_json_values


class TestEndpointUtils:
    def test_schema_fields_constructor(self, db):
        worked = 0
        for Schema in db.interface:
            schema = Schema(many=True)
            try:
                construct_schema_fields_object(schema)
                worked += 1
            except:
                continue
        assert worked == len(db.interface)

    def test_schema_json_examples(self, db):
        '''
         Autogenerating json examples for fields
        '''
        Sample = db.interface.sample(many=True)

        sample_json = {}

        for field, type_, name in get_schema_field_items(Sample):
            sample_json[name] = get_field_json_values(type_)
        
        assert "Some autogenerated text" == sample_json['name']


