name: Sparrow continuous integration
on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main, develop]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      # We had to remove submodule recursion due to changes in pgMemento
      - name: Update submodules
        run: git submodule update --init

      - uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      # Bundling
      - name: Install software for local development 
        run: make && sudo make install-dev

      - name: Run Sparrow core tests
        run: sparrow test

      - name: Run Sparrow integration tests
        run: sparrow test integration

